# Change these first
owner: dazser # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: DAZSER Web App (v2)
    url: https://www.dazser.net
    slug: v2
  - name: DAZSER Beta Web App (v3)
    url: https://beta.dazser.net
    slug: v3
  - name: DAZSER Payment Portal
    url: https://pay.dazser.com
    slug: pay
  - name: DAZSER Survey/Inspection Site
    url: https://survey.dazser.net/tampa
    slug: survey
  - name: Moodle
    url: https://moodle.dazser.net
    slug: moodle
  - name: Tampa
    url: http://tampa.dazser.com:8081
    slug: tampa
  - name: Birmingham
    url: http://birmingham.dazser.com:8080
    slug: birmingham
  - name: Baltimore
    url: http://baltimore.dazser.com:8080
    slug: baltimore
  - name: Orlando
    url: http://orlando.dazser.com:8080

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DAZSER Status
  introTitle: "**DAZSER** status page"
  introMessage: "Below is the status of all online DAZSER properties."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
